font_family FiraCode Nerd Font
font_size 16

# SPLIT
enabled_layouts splits
map super+a launch --location=split
map super+x close

map super+h neighboring_window left
map super+l neighboring_window right
map super+k neighboring_window up
map super+j neighboring_window down

map shift+super+h move_window left
map shift+super+l move_window right
map shift+super+k move_window up
map shift+super+j move_window down

# BORDERS
active_border_color   #33ccff
inactive_border_color #595959

window_margin_width 0
window_padding_width 0

window_border_width 4px
draw_minimal_borders no

draw_window_borders_for_single_window yes
single_window_margin_width 4

placement_strategy center

# SIZE ON OPENING
remember_window_size  no
initial_window_width  10000
initial_window_height 10000

# MISC
hide_window_decorations yes

allow_remote_control yes
listen_on unix:/tmp/kitty
